name: getSSMParameters

on:
  workflow_dispatch:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
  
permissions:
  contents: read
  pull-requests: write
  
jobs: 
  get-ssm-parameters:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Authenticate to AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      # - name: Set SSM Params as Env Vars
      #   run: | 
      #     /bin/bash ./githubBuild/getSsmParameters.sh