name: getSSMParameters

on:
  workflow_dispatch:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
  
permissions:
  contents: read
  pull-requests: write
  
jobs: 
  build-and-deploy-lambda:
    runs-on: ubuntu-24.04
    steps:
      - name: Set SSM Params as Env Vars
        uses: Bardavon-Health/actions-aws-ssm-params-to-env@v1.4.0
        with:
          ssm-path: /path/to/parameter