name: getSSMParameters

on:
  workflow_dispatch:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
  
permissions:
  contents: read
  pull-requests: write
  
jobs: 
  get-ssm-parameters:
    runs-on: ubuntu-24.04
    steps:
      - name: Set SSM Params as Env Vars
        run: | 
          /bin/bash ./githubBuild/getSSMParameters.sh